package com.edselmustapa.mywallet.ui.theme.old

import androidx.compose.ui.graphics.Color
import com.edselmustapa.mywallet.ui.theme.ThemeColors

val oldColor = ThemeColors(
    md_theme_light_primary = Color(0xFF00696D),
    md_theme_light_onPrimary = Color(0xFFFFFFFF),
    md_theme_light_primaryContainer = Color(0xFF6FF6FC),
    md_theme_light_onPrimaryContainer = Color(0xFF002021),
    md_theme_light_secondary = Color(0xFF4A6364),
    md_theme_light_onSecondary = Color(0xFFFFFFFF),
    md_theme_light_secondaryContainer = Color(0xFFCCE8E9),
    md_theme_light_onSecondaryContainer = Color(0xFF041F20),
    md_theme_light_tertiary = Color(0xFF4D5F7C),
    md_theme_light_onTertiary = Color(0xFFFFFFFF),
    md_theme_light_tertiaryContainer = Color(0xFFD5E3FF),
    md_theme_light_onTertiaryContainer = Color(0xFF071C36),
    md_theme_light_error = Color(0xFFBA1A1A),
    md_theme_light_errorContainer = Color(0xFFFFDAD6),
    md_theme_light_onError = Color(0xFFFFFFFF),
    md_theme_light_onErrorContainer = Color(0xFF410002),
    md_theme_light_background = Color(0xFFFAFDFC),
    md_theme_light_onBackground = Color(0xFF191C1C),
    md_theme_light_surface = Color(0xFFFAFDFC),
    md_theme_light_onSurface = Color(0xFF191C1C),
    md_theme_light_surfaceVariant = Color(0xFFDAE4E4),
    md_theme_light_onSurfaceVariant = Color(0xFF3F4949),
    md_theme_light_outline = Color(0xFF6F7979),
    md_theme_light_inverseOnSurface = Color(0xFFEFF1F1),
    md_theme_light_inverseSurface = Color(0xFF2D3131),
    md_theme_light_inversePrimary = Color(0xFF4CD9DF),
    md_theme_light_shadow = Color(0xFF000000),
    md_theme_light_surfaceTint = Color(0xFF00696D),
    md_theme_light_outlineVariant = Color(0xFFBEC8C8),
    md_theme_light_scrim = Color(0xFF000000),

    md_theme_dark_primary = Color(0xFF4CD9DF),
    md_theme_dark_onPrimary = Color(0xFF003739),
    md_theme_dark_primaryContainer = Color(0xFF004F52),
    md_theme_dark_onPrimaryContainer = Color(0xFF6FF6FC),
    md_theme_dark_secondary = Color(0xFFB0CCCD),
    md_theme_dark_onSecondary = Color(0xFF1B3435),
    md_theme_dark_secondaryContainer = Color(0xFF324B4C),
    md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E9),
    md_theme_dark_tertiary = Color(0xFFB5C7E9),
    md_theme_dark_onTertiary = Color(0xFF1F314C),
    md_theme_dark_tertiaryContainer = Color(0xFF354764),
    md_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF),
    md_theme_dark_error = Color(0xFFFFB4AB),
    md_theme_dark_errorContainer = Color(0xFF93000A),
    md_theme_dark_onError = Color(0xFF690005),
    md_theme_dark_onErrorContainer = Color(0xFFFFDAD6),
    md_theme_dark_background = Color(0xFF191C1C),
    md_theme_dark_onBackground = Color(0xFFE0E3E2),
    md_theme_dark_surface = Color(0xFF191C1C),
    md_theme_dark_onSurface = Color(0xFFE0E3E2),
    md_theme_dark_surfaceVariant = Color(0xFF3F4949),
    md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8),
    md_theme_dark_outline = Color(0xFF899393),
    md_theme_dark_inverseOnSurface = Color(0xFF191C1C),
    md_theme_dark_inverseSurface = Color(0xFFE0E3E2),
    md_theme_dark_inversePrimary = Color(0xFF00696D),
    md_theme_dark_shadow = Color(0xFF000000),
    md_theme_dark_surfaceTint = Color(0xFF4CD9DF),
    md_theme_dark_outlineVariant = Color(0xFF3F4949),
    md_theme_dark_scrim = Color(0xFF000000),


    seed = Color(0xFF009EA3),
    CustomColor1 = Color(0xFF211300),
    light_CustomColor1 = Color(0xFF805600),
    light_onCustomColor1 = Color(0xFFFFFFFF),
    light_CustomColor1Container = Color(0xFFFFDDB0),
    light_onCustomColor1Container = Color(0xFF291800),
    dark_CustomColor1 = Color(0xFFFEBA4B),
    dark_onCustomColor1 = Color(0xFF442B00),
    dark_CustomColor1Container = Color(0xFF614000),
    dark_onCustomColor1Container = Color(0xFFFFDDB0),
)